import { useState } from "react";

import RoleSelection from "./components/RoleSelection";
import LanguageSelection from "./components/LanguageSelection";
import Consent from "./components/Consent";
import PatientRegistration from "./components/PatientRegistration";
import CaseTaking from "./components/CaseTaking";
import DoctorDashboard from "./components/DoctorDashboard";
import DocumentUpload from "./components/DocumentUpload";
import PhysicianLogin from "./components/PhysicianLogin";
function App() {
  const [screen, setScreen] = useState("role");

  const [language, setLanguage] = useState("en");
  const [patientId, setPatientId] = useState(null);
  const [patientInfo, setPatientInfo] = useState(null);
  const [caseId, setCaseId] = useState(null);

  // -----------------------------
  // ROLE SELECTION
  // -----------------------------
  if (screen === "role") {
    return (
      <RoleSelection
        onSelect={(role) => {
          if (role === "patient") {
            setScreen("language");
          }

          if (role === "physician") {
            setScreen("physician-login");
          }
        }}
      />
    );
  }

  // -----------------------------
  // PATIENT: LANGUAGE
  // -----------------------------
  if (screen === "language") {
    return (
      <LanguageSelection
        onSelect={(selectedLanguage) => {
          setLanguage(selectedLanguage);
          setScreen("consent");
        }}
      />
    );
  }

  // -----------------------------
  // PATIENT: CONSENT
  // -----------------------------
  if (screen === "consent") {
    return (
      <Consent
  language={language}
  onAgree={() => setScreen("registration")}
  onBack={() => setScreen("language")}
/>
    );
  }

  // -----------------------------
  // PATIENT: REGISTRATION
  // -----------------------------
  if (screen === "registration") {
  return (
    <PatientRegistration
      language={language}
      onRegistered={(patient) => {
  setPatientId(patient.id);
  setPatientInfo(patient);
  setScreen("case");
}}
    />
  );
}

  // -----------------------------
  // PATIENT: CASE TAKING
  // -----------------------------
  if (screen === "case") {
  return (
    <CaseTaking
      patientId={patientId}
      patientInfo={patientInfo}
      language={language}
      onComplete={(id) => {
        setCaseId(id);
        setScreen("documents");
      }}
    />
  );
}

  if (screen === "documents") {
  return (
    <DocumentUpload
      caseId={caseId}
      onComplete={() => {
        setScreen("patient-complete");
      }}
    />
  );
}

  // -----------------------------
  // PATIENT: COMPLETE
  // -----------------------------
  if (screen === "patient-complete") {
  const printSlip = () => {
    window.print();
  };

  return (
    <div className="app">
      <div className="print-slip">
        <h1>MediKiosk</h1>
        <h2>OPD Consultation Slip</h2>

        <hr />

        <p>
          <strong>Patient ID:</strong> {patientId}
        </p>

        <p>
          <strong>Case ID:</strong> {caseId}
        </p>

        <p>
          <strong>Date:</strong>{" "}
          {new Date().toLocaleDateString()}
        </p>

        <hr />

        <p>
          Your clinical information has been
          recorded successfully.
        </p>

        <p>
          Please proceed to the designated
          OPD/doctor for consultation.
        </p>

        <div className="print-only-note">
          This slip is generated by MediKiosk.
        </div>
      </div>

      <button onClick={printSlip}>
  🖨️ Print Slip
</button>

<button
  onClick={() => {
    setPatientId(null);
    setCaseId(null);
    setLanguage("en");
    setScreen("role");
  }}
>
  🏠 Go to Home
</button>
    </div>
  );
}

  // -----------------------------
  // PHYSICIAN LOGIN
  // -----------------------------
  if (screen === "physician-login") {
  return (
    <PhysicianLogin
      onLogin={() => setScreen("dashboard")}
      onBack={() => setScreen("role")}
    />
  );
}

  // -----------------------------
  // DOCTOR DASHBOARD
  // -----------------------------
  if (screen === "dashboard") {
    return (
      <DoctorDashboard caseId={caseId} />
    );
  }

  return null;
}

export default App;